#!/bin/bash
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "[\"<Control>F1\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "[\"<Control>F2\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "[\"<Control>F3\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "[\"<Control>F4\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "[\"<Control>F5\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "[\"<Control>F6\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "[\"<Control>F7\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "[\"<Control>F8\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "[\"<Control>F9\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10 "[\"<Control>F10\"]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-11 "[\"<Control>F11\"]"

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "[\"<Super><Control>F1\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "[\"<Super><Control>F2\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "[\"<Super><Control>F3\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "[\"<Super><Control>F4\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "[\"<Super><Control>F5\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "[\"<Super><Control>F6\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "[\"<Super><Control>F7\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "[\"<Super><Control>F8\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "[\"<Super><Control>F9\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10 "[\"<Super><Control>F10\"]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-11 "[\"<Super><Control>F11\"]"
